splash = false
preload = /home/helomo/helomoTheme/Lumin.png
wallpaper {
    monitor = eDP-1
    path = /home/helomo/helomoTheme/Lumin.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/helomo/helomoTheme/Lumin.png
    fit_mode = cover
}