splash = false
preload = /home/helomo/helomoTheme/kazuha.jpg
wallpaper {
    monitor = eDP-1
    path = /home/helomo/helomoTheme/kazuha.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/helomo/helomoTheme/kazuha.jpg
    fit_mode = cover
}